name: cargy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  video_player: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Ellipse1.png
    - assets/Ellipse2.png
    - assets/Ellipse3.png
    - assets/Group 338.png
    - assets/workshops/workshop1.png
    - assets/workshops/workshop2.png
    - assets/workshops/workshop3.png
    - assets/workshops/workshop4.png
    - assets/workshops/workshop5.png
    - assets/workshops/workshop6.png
    - assets/logos/toyota.png
    - assets/logos/hyundai.png
    - assets/logos/tesla.png
    - assets/logos/bmw.png
    - assets/videos/ForBiggerBlazes.mp4
    - assets/videos/ForBiggerEscapes.mp4
    - assets/videos/ForBiggerJoyrides.mp4
